"""Precomputed default result, so the deployed app opens without computing.

The app used to run the full claims analysis, the joint-sensitivity sweep and
the tidal-cycle simulation on every cold page load - about a minute of solver
work each time, on every visitor and every rerun. On Streamlit Community Cloud,
where the container has a fraction of a core, that pinned the CPU and the
platform throttled the app, which made it slower still. The cure is to not
compute on load at all: ship the default result and read it back.

The bundle is a pickle of the default-config artifacts. It is regenerated by
``scripts/precompute_default.py`` and committed. Two safeguards keep it from ever
serving a wrong or stale answer:

* it carries a content fingerprint of the whole ``tidetwin`` package, checked on
  load; if any solver source changed since it was built, the bundle is ignored
  and the app falls back to computing on demand;
* every load is wrapped so that any failure - a missing file, an unpicklable
  object after a dependency bump - returns ``None`` rather than raising, and the
  app then shows its "run the analysis" landing instead of a broken page.

So the bundle is a pure best-effort accelerator: when it is valid the app is
instant, and when it is not the app is exactly as correct, only slower.
"""

from __future__ import annotations

import hashlib
import pickle
from pathlib import Path
from typing import Any

__all__ = ["BUNDLE_PATH", "source_fingerprint", "build_bundle", "save_bundle", "load_bundle"]

_PKG = Path(__file__).resolve().parent
BUNDLE_PATH = _PKG / "data" / "precomputed" / "default_bundle.pkl"

#: Bumped by hand if the bundle's structure changes in a way the fingerprint
#: alone would not catch. Part of the stored dict and checked on load.
_BUNDLE_VERSION = 2

#: Modules that render results but never enter the computation the bundle stores.
#: They are excluded from the fingerprint so that a purely cosmetic edit does not
#: force a two-minute regeneration. Nothing here is imported by run_full, the
#: sensitivity sweep or the tidal-cycle simulation - if that ever changes, move
#: the module out of this set.
_PRESENTATION_ONLY: frozenset[str] = frozenset({"ui.py", "diagram.py", "buildinfo.py"})


def source_fingerprint() -> str:
    """A content hash of every ``tidetwin`` source file.

    Content, not modification time: a git checkout on the deploy host has fresh
    mtimes but identical bytes, so an mtime hash would never match there. Files
    are read in text mode, which normalises CRLF to LF, so the hash agrees
    between the Windows machine that built the bundle and the Linux container
    that loads it.
    """
    h = hashlib.sha256()
    h.update(str(_BUNDLE_VERSION).encode())
    try:
        for p in sorted(_PKG.rglob("*.py"), key=lambda q: q.as_posix()):
            if p.name in _PRESENTATION_ONLY:
                continue
            h.update(p.relative_to(_PKG).as_posix().encode())
            with open(p, encoding="utf-8") as fh:
                h.update(fh.read().encode("utf-8"))
    except OSError:
        return "unavailable"
    return h.hexdigest()[:16]


def build_bundle(cfg: Any = None) -> dict[str, Any]:
    """Compute the full default result: claims, sensitivity sweep, tidal cycle."""
    import numpy as np

    from .analysis import normalise, run_full
    from .appdefaults import default_config
    from .geometry.oc4 import (
        brace_chord_joints,
        build_jacket,
        load_tables,
        sensor_pair,
    )
    from .robustness import joint_sensitivity, ljf_sensitivity
    from .simulate import simulate_cycle

    cfg = cfg if cfg is not None else default_config()
    full = run_full(cfg)

    ncfg, _notes = normalise(cfg)
    con = ncfg.constituents()
    tables = load_tables()
    joints = tuple(sorted(brace_chord_joints(tables)))
    sensitivity = (
        ljf_sensitivity(con, ncfg.hydro(), joint_id=ncfg.joint_id,
                        offset_m=ncfg.sensor_offset_m, n_theta=12),
        joint_sensitivity(con, ncfg.hydro(), joints, offset_m=0.4, n_theta=12),
    )

    pair = sensor_pair(tables, ncfg.joint_id, ncfg.sensor_offset_m,
                       np.radians(ncfg.sensor_theta_deg))
    build = build_jacket(ljf_model=ncfg.ljf_model, tables=tables)
    cycle = simulate_cycle(build, pair, ncfg.constituents(), ncfg.hydro(), n_frames=36)

    return {
        "version": _BUNDLE_VERSION,
        "fingerprint": source_fingerprint(),
        "cfg": cfg,
        "full": full,
        "sensitivity": sensitivity,
        "cycle": cycle,
    }


def save_bundle(cfg: Any = None) -> tuple[Path, int]:
    """Build and write the bundle. Returns its path and size in bytes."""
    BUNDLE_PATH.parent.mkdir(parents=True, exist_ok=True)
    bundle = build_bundle(cfg)
    with open(BUNDLE_PATH, "wb") as fh:
        pickle.dump(bundle, fh, protocol=4)
    return BUNDLE_PATH, BUNDLE_PATH.stat().st_size


#: Why the last load_bundle() returned None, for the app's Diagnostics panel.
#: The deployed app hides tracebacks and load_bundle degrades silently, so
#: without this a bundle that fails only on the deploy host is invisible.
_LAST_LOAD_ERROR: str | None = None


def last_load_error() -> str | None:
    """A human-readable reason the most recent load_bundle() returned None."""
    return _LAST_LOAD_ERROR


def load_bundle() -> dict[str, Any] | None:
    """Load the committed bundle if it is present and current, else ``None``.

    Never raises: a missing file, a fingerprint mismatch, or an unpicklable
    object all return ``None`` so the caller degrades to computing on demand.
    The reason is recorded in ``last_load_error()`` for the Diagnostics panel.
    """
    global _LAST_LOAD_ERROR
    try:
        if not BUNDLE_PATH.is_file():
            _LAST_LOAD_ERROR = f"file not found at {BUNDLE_PATH}"
            return None
        with open(BUNDLE_PATH, "rb") as fh:
            bundle = pickle.load(fh)
        if bundle.get("version") != _BUNDLE_VERSION:
            _LAST_LOAD_ERROR = (
                f"version {bundle.get('version')!r} != expected {_BUNDLE_VERSION!r}"
            )
            return None
        want = source_fingerprint()
        if bundle.get("fingerprint") != want:
            _LAST_LOAD_ERROR = (
                f"fingerprint {bundle.get('fingerprint')!r} != source {want!r}"
            )
            return None
        _LAST_LOAD_ERROR = None
        return bundle
    except Exception as exc:  # noqa: BLE001 - a bad bundle must degrade, never crash the app
        _LAST_LOAD_ERROR = f"{type(exc).__name__}: {exc}"
        return None
